# Logistic Regression

Modeling using testing/training data, addressing oversampling using SMOTEEN

## Importing Packages

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

## Loading Data

In [2]:
thyroid_train_labels = pd.read_csv("train_labels.csv")
thyroid_train_labels

      0
0     0
1     0
2     0
3     0
4     0
...  ..
7328  1
7329  0
7330  0
7331  0
7332  0

[7333 rows x 1 columns]

In [3]:
thyroid_train = pd.read_csv("train.csv")
thyroid_train

,age,sex,FTI,T3,T4U,TSH,TT4,I131 treatment,goitre,hypopituitary,...,query on thyroxine,sick,thyroid surgery,tumor,FTI_missing,T3_missing,T4U_missing,TSH_missing,TT4_missing,sex_missing
0,45,0,108.442729,1.931772,0.956728,1.204034,103.290203,0,0,0,...,0,0,0,0,1,1,1,1,1,0
1,23,0,109.690971,1.700000,0.964004,0.800000,107.000000,0,0,0,...,0,0,0,0,1,0,1,0,0,0
2,71,1,107.000000,1.700000,1.060000,2.700000,113.000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,46,0,136.000000,1.917229,0.860000,0.060000,117.000000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,83,0,160.000000,1.775536,0.920000,1.800000,147.000000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7328,77,0,81.000000,1.614555,1.020000,36.000000,82.000000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7329,64,0,108.000000,1.776734,0.920000,1.400000,99.000000,0,0,0,...,1,0,0,0,0,1,0,0,0,0
7330,24,1,106.000000,1.700000,1.000000,1.300000,106.000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7331,62,0,93.000000,1.900000,0.710000,1.600000,66.000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7332,49,1,71.000000,1.929114,1.140000,17.905366,81.000000,0,0,0,...,0,0,0,0,0,1,0,1,0,0

In [4]:
thyroid_test = pd.read_csv("test.csv")
thyroid_test

,age,sex,FTI,T3,T4U,TSH,TT4,I131 treatment,goitre,hypopituitary,...,query on thyroxine,sick,thyroid surgery,tumor,FTI_missing,T3_missing,T4U_missing,TSH_missing,TT4_missing,sex_missing
0,23,0,120.0,2.300000,1.25,3.70,150.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,40,1,90.0,2.300000,0.96,1.30,87.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,22,1,80.0,2.300000,1.01,2.10,81.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,34,0,101.0,1.800000,0.97,0.73,97.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,79,0,100.0,1.300000,0.92,2.40,92.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,68,0,93.0,1.896305,1.02,1.20,95.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1830,87,0,147.0,1.700000,0.96,2.50,140.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1831,57,1,256.0,3.700000,0.95,0.05,244.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1832,50,0,103.0,2.500000,1.11,1.80,114.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1833,66,1,86.0,1.900000,0.84,0.90,72.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
thyroid_test_labels = pd.read_csv("test_labels.csv")
thyroid_test_labels

      0
0     0
1     0
2     0
3     0
4     0
...  ..
1829  0
1830  0
1831  2
1832  0
1833  0

[1834 rows x 1 columns]

## Setting up X and Y

In [6]:
X_train = thyroid_train
X_train.columns

Index(['age', 'sex', 'FTI', 'T3', 'T4U', 'TSH', 'TT4', 'I131 treatment',
       'goitre', 'hypopituitary', 'lithium', 'on antithyroid medication',
       'on thyroxine', 'pregnant', 'psych', 'query hyperthyroid',
       'query hypothyroid', 'query on thyroxine', 'sick', 'thyroid surgery',
       'tumor', 'FTI_missing', 'T3_missing', 'T4U_missing', 'TSH_missing',
       'TT4_missing', 'sex_missing'],
      dtype='object')

In [7]:
y_train = thyroid_train_labels
y_train.shape

(7333, 1)

In [8]:
X_test = thyroid_test
X_test.columns

Index(['age', 'sex', 'FTI', 'T3', 'T4U', 'TSH', 'TT4', 'I131 treatment',
       'goitre', 'hypopituitary', 'lithium', 'on antithyroid medication',
       'on thyroxine', 'pregnant', 'psych', 'query hyperthyroid',
       'query hypothyroid', 'query on thyroxine', 'sick', 'thyroid surgery',
       'tumor', 'FTI_missing', 'T3_missing', 'T4U_missing', 'TSH_missing',
       'TT4_missing', 'sex_missing'],
      dtype='object')

In [9]:
y_test = thyroid_test_labels
y_test.shape

(1834, 1)

In [10]:
print("y_train distribution:\n", y_train.value_counts())
print("y_test distribution:\n", y_test.value_counts())

y_train distribution:
 0
0    6713
1     474
2     146
Name: count, dtype: int64
y_test distribution:
 0
0    1679
1     119
2      36
Name: count, dtype: int64

1 = hypothyroid 2 = hyperthyroid 0 = neither hyperthyroid or hypothyroid

## Scaling Before Resampling

In [11]:
ss = StandardScaler()

X_train_scaled = ss.fit_transform(X_train)

X_test_scaled = ss.transform(X_test)

## SMOTEENN Sampling for Class Imbalance

In [12]:
#!pip install imbalanced-learn

In [13]:
from imblearn.combine import SMOTEENN

In [14]:
smote_enn = SMOTEENN(random_state = 6740) 
X_train_resampled_smote_enn, y_train_resampled_smote_enn = smote_enn.fit_resample(X_train_scaled, y_train)

In [15]:
print("y_train distribution:\n", y_train_resampled_smote_enn.value_counts())
#print("y_test distribution:\n", y_test.value_counts())

y_train distribution:
 0
2    6703
1    6587
0    5867
Name: count, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
td_lr = LogisticRegression(class_weight='balanced',random_state=6740)
td_lr.fit(X_train_resampled_smote_enn, y_train_resampled_smote_enn)

LogisticRegression(class_weight='balanced', random_state=6740)

In [17]:
y_pred = td_lr.predict(X_test_scaled)

In [18]:
# Predict probabilities
y_prob = td_lr.predict_proba(X_test_scaled)

In [19]:
y_prob.shape

(1834, 3)